# llms.txt: https://bolasblack.github.io/alcatraz/llms.txt
#:schema https://raw.githubusercontent.com/bolasblack/alcatraz/refs/heads/master/alca-config.schema.json

includes = ['./.alca.*.toml']
image = 'ghcr.io/bolasblack/alca-debian:latest'

workdir_exclude = [
  '.env',
  'node_modules',
  '.alca.mounts',
]

mounts = [
  '.alca.mounts/mise:/root/.local/share/mise',
  '.alca.mounts/extra-bin:/extra-bin',
  '.alca.mounts/extra-scripts:/extra-scripts',
]

[commands]
# prepare the environment
up = """
apt install -y vim tmux

echo '
export PATH="/root/.local/share/mise/shims:$PATH"
export PATH="/extra-bin:$PATH"
' >> ~/.profile
. ~/.profile

[ -x /extra-scripts/source.sh ] && . /extra-scripts/source.sh

mise trust -a
mise install

[ -x /extra-scripts/init.sh ] && /extra-scripts/init.sh
"""
enter = """
[ -x /extra-scripts/source.sh ] && . /extra-scripts/source.sh
. ~/.profile
"""

[envs]
IS_SANDBOX = '1'
